[ch [title Syntax Extensions]

    [u:ins-file path=01_comments.pml]
    [u:ins-file path=02_attributes.pml]
    [u:ins-file path=03_escape_sequences.pml]
    [u:ins-file path=04_namespaces.pml]
    [u:ins-file path=05_named_closing_tags.pml]
    [u:ins-file path=06_virtual_root_node.pml]
    [u:ins-file path=07_processing_instructions.pml]
]
